### ISSUE TITLE
Is there a way to add participants to an Event using EKParticipant?

### ISSUE THREAD

**Issue by akash-kr** [AlbertMontserrat/AMGCalendarManager#2]

**Comment by AlbertMontserrat** [comment]
https://developer.apple.com/documentation/eventkit/ekparticipant

It says:
"Do not create EKParticipant objects directly. Instead, use the property attendees on
EKCalendarItem
to return an array of EKParticipant objects.

Event Kit cannot add participants to an event nor change participant information. Use the properties in this class to get information about a participant."

**Comment by akash-kr** [comment]
I just tried the below approach for adding participants when creating an event and it works. That's the reason I asked if this could be made part of the library as it would be very helpful.

```
@IBAction func click_event(_ sender: Any) {
        
        AMGCalendarManager.shared.createEvent { (event) in
            guard let event = event else { return }
            
            event.title = "Meeting with Mr.\(Int(arc4random_uniform(2000)))"
            event.startDate = Date()
            event.endDate = event.startDate.addingTimeInterval(Double(arc4random_uniform(24)) * 60 * 60)
            
            //other options
            event.notes = "Don't forget to bring the meeting memos"
            event.location = "Room \(Int(arc4random_uniform(100)))"
            event.availability = .free
            
            var attendees = [EKParticipant]()
            if let attendee = self.createParticipant(email: "testing@gmail.com") {
                attendees.append(attendee)
            }
            
            event.setValue(attendees, forKey: "attendees")
            
            AMGCalendarManager.shared.saveEvent(event: event, completion: { (error) in
                //self.refreshEvents()
                print(event)
            })
        }

    }
    
    private func createParticipant(email: String) -> EKParticipant? {
        let clazz: AnyClass? = NSClassFromString("EKAttendee")
        if let type = clazz as? NSObject.Type {
            let attendee = type.init()
            attendee.setValue(email, forKey: "emailAddress")
            return attendee as? EKParticipant
        }
        return nil
    }
```

**Comment by AlbertMontserrat** [comment]
Ok. But I don't know if Apple aprove a private SDK. 
Anyway, my lib's goal is to provide a easy way to create and manage Calendar events, permisions, etc. The configuration of the EKEvent is up to you. It's not the goal of the library. Because the use of the EKEvent is different for every situation.

**Comment by akash-kr** [comment]
Fair enough.

But what about adding the "Privacy - Calendars Usage Description" to info.plist. Can you update the documentation to show that and also maybe handle the ```EKEventStore.authorizationStatus``` to determine if the user has given permission to access the calendar?

**Comment by AlbertMontserrat** [comment]
If the user has denied accés, any method of the library will return an specific error to inform de developer that this was the issue.

**Comment by AlbertMontserrat** [comment]
Info.plist description in installations done! :)
